// <auto-generated />
using API_Contacts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Contacts.Migrations
{
    [DbContext(typeof(DBContactsContext))]
    partial class DBContactsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("API_Contacts.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("API_Contacts.ContactSkill", b =>
                {
                    b.Property<int>("IdContact")
                        .HasColumnName("Id_Contact")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSkill")
                        .HasColumnName("Id_Skill")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdContact", "IdSkill");

                    b.HasIndex("IdSkill");

                    b.ToTable("ContactSkill");
                });

            modelBuilder.Entity("API_Contacts.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("SkillName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Skill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillLevel = "Bof",
                            SkillName = "Courage"
                        });
                });

            modelBuilder.Entity("API_Contacts.ContactSkill", b =>
                {
                    b.HasOne("API_Contacts.Contact", "IdContactNavigation")
                        .WithMany("ContactSkill")
                        .HasForeignKey("IdContact")
                        .HasConstraintName("FK_ContactSkill_Contact")
                        .IsRequired();

                    b.HasOne("API_Contacts.Skill", "IdSkillNavigation")
                        .WithMany("ContactSkill")
                        .HasForeignKey("IdSkill")
                        .HasConstraintName("FK_ContactSkill_Skill")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
